### ISSUE TITLE
Allow tasty-quickcheck-0.11 ?

### ISSUE THREAD

**Issue by andreasabel** [nikita-volkov/lawful-conversions#1]
https://github.com/nikita-volkov/lawful-conversions/blob/d66c8e0aaf2b8521d57e6198e201c7000d0e3ff9/lawful-conversions.cabal#L178

Is the bound `tasty-quickcheck < 0.11` needed or was this an oversight?
- https://github.com/commercialhaskell/stackage/issues/7597

**Comment by nikita-volkov** [comment]
An oversight. Will fix in a moment. Thanks.

**Comment by nikita-volkov** [comment]
Fixed
